'use strict';
var BUTTON = require("../button");
var Constant = {};
Constant[BUTTON.UP]     = 12;
Constant[BUTTON.DOWN]   = 13;
Constant[BUTTON.LEFT]   = 14;
Constant[BUTTON.RIGHT]  = 15;
Constant[BUTTON.MENU]   = 16;
Constant[BUTTON.A]      = 1;
Constant[BUTTON.B]      = 0;
Constant[BUTTON.X]      = 2;
Constant[BUTTON.Y]      = 3;
Constant[BUTTON.L1]     = 4;
Constant[BUTTON.R1]     = 5;
Constant[BUTTON.L2]     = 6;
Constant[BUTTON.R2]     = 7;
Constant[BUTTON.SELECT] = 8;
Constant[BUTTON.START]  = 9;
Constant[BUTTON.L3]     = 10;
Constant[BUTTON.R3]     = 11;

module.exports = Constant;
